version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.0
jobs:
  test-2.0:
    docker:
      - image: microsoft/dotnet:2.0-sdk-jessie
    steps:
      - run:
          name: install packages
          command: apt-get -q update && apt-get install -qy awscli
      - checkout
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.EventSource -f netstandard1.4
      - run: dotnet test test/LaunchDarkly.EventSource.Tests/LaunchDarkly.EventSource.Tests.csproj -f netcoreapp2.0
