version: 2
jobs:
  test-1.1:
    docker:
      - image: microsoft/dotnet:1.1-sdk
    steps:
      - run:
          name: install packages
          command: apt-get -q update && apt-get install -qy awscli
      - checkout
      - run: aws s3 cp s3://launchdarkly-pastebin/ci/dotnet/LaunchDarkly.EventSource.snk LaunchDarkly.EventSource.snk
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.EventSource -f netstandard1.4
      - run: dotnet test test/LaunchDarkly.EventSource.Tests/LaunchDarkly.EventSource.Tests.csproj -f netcoreapp1.1
