version: 2.1

orbs:
  win: circleci/windows@1.0.0

workflows:
  version: 2
  test:
    jobs:
      - test-netcore:
          name: .NET Core 2.1
          docker-image: mcr.microsoft.com/dotnet/core/sdk:2.1-focal
          test-target-framework: netcoreapp2.1
      - test-netcore:
          name: .NET Core 3.1
          docker-image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
          test-target-framework: netcoreapp3.1
      - test-netcore:
          name: .NET 5.0
          docker-image: mcr.microsoft.com/dotnet/sdk:5.0-focal
          test-target-framework: net5.0
      - test-windows-netframework-4-6-1:
          name: .NET Framework 4.6.1

jobs:
  test-netcore:
    parameters:
      docker-image:
        type: string
      test-target-framework:
        type: string
    docker:
      - image: <<parameters.docker-image>>
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      TESTFRAMEWORK: <<parameters.test-target-framework>>
    steps:
      - run:
          name: install packages
          command: apt-get -q update && apt-get install -qy awscli
      - checkout
      - run: dotnet build src/LaunchDarkly.EventSource -f netstandard2.0
      - run: dotnet test test/LaunchDarkly.EventSource.Tests/LaunchDarkly.EventSource.Tests.csproj -f <<parameters.test-target-framework>>

  test-windows-netframework-4-6-1:
    executor:
      name: win/vs2019
      shell: powershell.exe
    environment:
      TESTFRAMEWORK: net461
    steps:
      - checkout
      - run: dotnet build src/LaunchDarkly.EventSource -f net452
      - run: dotnet test test/LaunchDarkly.EventSource.Tests/LaunchDarkly.EventSource.Tests.csproj -f net461
